### ISSUE TITLE
RAP2点击仓库一直加载，不显示数据，控制台报错

### ISSUE THREAD

**Issue by hu970804** [thx/RAP#1158]
utils.js:240 uncaught at c TypeError: t.match is not a function
    at Object.value (http://rap2.taobao.org/static/js/main.c05cfa29.js:6:15131)
    at Object.diff (http://rap2.taobao.org/static/js/main.c05cfa29.js:6:13676)
    at Object.properties (http://rap2.taobao.org/static/js/main.c05cfa29.js:6:16273)
    at Object.diff (http://rap2.taobao.org/static/js/main.c05cfa29.js:6:13696)
    at Object.items (http://rap2.taobao.org/static/js/main.c05cfa29.js:6:17237)
    at Object.diff (http://rap2.taobao.org/static/js/main.c05cfa29.js:6:13721)
    at Object.properties (http://rap2.taobao.org/static/js/main.c05cfa29.js:6:16273)
    at Object.diff (http://rap2.taobao.org/static/js/main.c05cfa29.js:6:13696)
    at Object.r [as valid] (http://rap2.taobao.org/static/js/main.c05cfa29.js:6:13525)
    at t.value (http://rap2.taobao.org/static/js/2.614ea7b6.chunk.js:2:1026)

**Comment by Aresxiao** [comment]
我有时候也遇到这样的问题。解决了吗
