### ISSUE TITLE
Rap2 注册不了进不去

### ISSUE THREAD

**Issue by hanouba** [thx/RAP#1243]

**Comment by javase** [comment]
是不是报错：
`technical details
Could not open Hibernate Session for transaction; nested exception is org.hibernate.TransactionException: JDBC begin transaction failed:
org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.TransactionException: JDBC begin transaction failed: at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:541) at `

**Comment by hanouba** [comment]
没有任何报错,就是点击注册没反应,我用老账户登录不进去,用老账户注册没反应,用新账户注册能登录,但是页面空白的,啥也没有;



han_belief@163.com
 
发件人： HeppyLemon
发送时间： 2018-08-01 16:01
收件人： thx/RAP
抄送： HanSir_belief; Author
主题： Re: [thx/RAP] Rap2 注册不了进不去 (#1243)
是不是报错：
technical details Could not open Hibernate Session for transaction; nested exception is org.hibernate.TransactionException: JDBC begin transaction failed: org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.TransactionException: JDBC begin transaction failed: at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:541) at
