### ISSUE TITLE
请教个部署问题： this web application instance has been stopped already

### ISSUE THREAD

**Issue by fahai** [thx/RAP#397]
## 概述  
tomcate版本：8.0.32
redis版本：3.0.3
MYSQL版本：5.6.26-enterprise-commercial-advanced
脚本导入正常，通过mysql命令连接可看到所建的表。
```  
mysql> show tables;
+------------------------------------+
| Tables_in_rap_db                   |
+------------------------------------+
| tb_action                          |
| tb_action_and_page                 |
| tb_check_in                        |
| tb_complex_parameter_list_mapping  |
| tb_corporation                     |
| tb_corporation_and_user            |
| tb_group                           |
| tb_module                          |
| tb_notification                    |
| tb_page                            |
| tb_parameter                       |
| tb_production_line                 |
| tb_project                         |
| tb_project_and_user                |
| tb_request_parameter_list_mapping  |
| tb_response_parameter_list_mapping |
| tb_role                            |
| tb_role_and_user                   |
| tb_rule                            |
| tb_user                            |
| tb_user_settings                   |
| tb_workspace                       |
| tb_workspace_save                  |
+------------------------------------+
23 rows in set (0.00 sec)  
```  
redis启动，可正常set和get。
tomcat未部署RAP前，可正常访问http://IP:8080页面。
把tomcat的webapps目录的ROOT目录删除，根据部署手册，把war解压到ROOT目录，war没有放置在webapps目录(放置war和不放置war两种方式都试过，日志报错是一样的)。

## tomcat启动命令输出    
```  
[sfapp@cnsz22vl0399:/home/sfapp/tomcat/bin]$sh startup.sh &
[1] 8855
[sfapp@cnsz22vl0399:/home/sfapp/tomcat/bin]$Using CATALINA_BASE:   /home/sfapp/tomcat
Using CATALINA_HOME:   /home/sfapp/tomcat
Using CATALINA_TMPDIR: /home/sfapp/tomcat/temp
Using JRE_HOME:        /usr/java/jdk1.8.0_60
Using CLASSPATH:       /home/sfapp/tomcat/bin/bootstrap.jar:/home/sfapp/tomcat/bin/tomcat-juli.jar
Tomcat started.
```  

## tomcat启动日志    
```  
23-Mar-2016 20:37:08.800 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.32
23-Mar-2016 20:37:08.801 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Feb 2 2016 19:34:53 UTC
23-Mar-2016 20:37:08.801 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.32.0
23-Mar-2016 20:37:08.801 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
23-Mar-2016 20:37:08.801 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            2.6.32-504.el6.x86_64
23-Mar-2016 20:37:08.801 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
23-Mar-2016 20:37:08.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/java/jdk1.8.0_60/jre
23-Mar-2016 20:37:08.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_60-b27
23-Mar-2016 20:37:08.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
23-Mar-2016 20:37:08.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /home/sfapp/tomcat
23-Mar-2016 20:37:08.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /home/sfapp/tomcat
23-Mar-2016 20:37:08.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/home/sfapp/tomcat/conf/logging.properties
23-Mar-2016 20:37:08.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
23-Mar-2016 20:37:08.802 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=/home/sfapp/tomcat/endorsed
23-Mar-2016 20:37:08.803 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/home/sfapp/tomcat
23-Mar-2016 20:37:08.803 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/home/sfapp/tomcat
23-Mar-2016 20:37:08.803 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/home/sfapp/tomcat/temp
23-Mar-2016 20:37:08.803 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
23-Mar-2016 20:37:08.918 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
23-Mar-2016 20:37:08.930 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
23-Mar-2016 20:37:08.932 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
23-Mar-2016 20:37:08.933 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
23-Mar-2016 20:37:08.933 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 705 ms
23-Mar-2016 20:37:08.950 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
23-Mar-2016 20:37:08.951 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.32
23-Mar-2016 20:37:08.957 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/sfapp/tomcat/webapps/docs
23-Mar-2016 20:37:39.141 INFO [localhost-startStop-1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [30,001] milliseconds.
23-Mar-2016 20:37:39.171 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/sfapp/tomcat/webapps/docs has finished in 30,214 ms
23-Mar-2016 20:37:39.171 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/sfapp/tomcat/webapps/manager
23-Mar-2016 20:37:39.233 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/sfapp/tomcat/webapps/manager has finished in 62 ms
23-Mar-2016 20:37:39.234 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/sfapp/tomcat/webapps/host-manager
23-Mar-2016 20:37:39.261 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/sfapp/tomcat/webapps/host-manager has finished in 28 ms
23-Mar-2016 20:37:39.262 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/sfapp/tomcat/webapps/examples
23-Mar-2016 20:37:39.651 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/sfapp/tomcat/webapps/examples has finished in 390 ms
23-Mar-2016 20:37:39.651 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /home/sfapp/tomcat/webapps/ROOT
23-Mar-2016 20:37:41.755 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
23-Mar-2016 20:37:42.508 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
23-Mar-2016 20:37:42.509 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
23-Mar-2016 20:37:42.514 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Log4j2-Log4j2Scheduled-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)
23-Mar-2016 20:37:42.518 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [commons-pool-EvictionTimer] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.util.TimerThread.mainLoop(Timer.java:552)
 java.util.TimerThread.run(Timer.java:505)
23-Mar-2016 20:37:42.524 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /home/sfapp/tomcat/webapps/ROOT has finished in 2,873 ms
23-Mar-2016 20:37:42.528 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
23-Mar-2016 20:37:42.533 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
23-Mar-2016 20:37:42.544 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 33610 ms  
```  

### 启动不报错，访问http://IP:8080后报错  
```  
23-Mar-2016 20:38:12.485 INFO [commons-pool-EvictionTimer] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.apache.commons.pool2.impl.EvictionConfig]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.commons.pool2.impl.EvictionConfig]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
        at org.apache.commons.pool2.impl.GenericObjectPool.evict(GenericObjectPool.java:746)
        at org.apache.commons.pool2.impl.BaseGenericObjectPool$Evictor.run(BaseGenericObjectPool.java:1026)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

**Comment by fahai** [comment]
补充一下，我是下载Releases：[https://github.com/thx/RAP/releases](https://github.com/thx/RAP/releases)上面的war包，RAP-0.14.1-SNAPSHOT.war和RAP-0.14.1-SNAPSHOT.war都部署过，一样的问题。

**Comment by Bosn** [comment]
没有遇到过...

从错误来看，是tomcat的问题。stackoverflow上面有很多解决方案，建议找最热的几个试一试：
http://stackoverflow.com/search?q=+Illegal+access%3A+this+web+application+instance+has+been+stopped+already.

例如有说道，重启tomcat/apache可以解决，是缓存问题导致。还有说可能因数据库未正常关闭导致。
另外亲的数据库也不是community版本，也可能是造成出现这个错误的原因。

**Comment by DoHello** [comment]
我跟你遇到的是同样的错误, 由于我很久没有使用过hibenate了, 遇到这个问题, 我第一个想到的是jar冲突
看了半天, 仔细一个一个感觉没毛病, 很疑惑
后来想了下, 直接下个稳定版本war按照步骤:这里一定要按照步骤看下, 然后打开的lib, 
手动版和自动版 对比了一下 发现少了以下依赖

hibernate-commons-annotations-5.0.1.Final.jar
hibernate-jpa-2.1-api-1.0.0.Final.jar
jandex-2.0.0.Final.jar
javassist-3.18.1-GA.jar
jboss-logging-3.3.0.Final.jar

这5个
这是pom的

>  <dependency>
            <groupId>org.hibernate.javax.persistence</groupId>
            <artifactId>hibernate-jpa-2.1-api</artifactId>
            <version>1.0.0.Final</version>
        </dependency>
        <dependency>
            <groupId>org.jboss</groupId>
            <artifactId>jandex</artifactId>
            <version>2.0.0.Final</version>
        </dependency>
        <dependency>
            <groupId>org.javassist</groupId>
            <artifactId>javassist</artifactId>
            <version>3.18.1-GA</version>
        </dependency>
        <dependency>
            <groupId>org.jboss.logging</groupId>
            <artifactId>jboss-logging</artifactId>
            <version>3.3.0.Final</version>
        </dependency>

好了,赶紧跑起来, 好久没用hibernate 看不懂, 真想用ssm把这重写了
