### ISSUE TITLE
linux部署协助：The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.

### ISSUE THREAD

**Issue by fahai** [thx/RAP#401]
之前提过这个问题：[https://github.com/thx/RAP/issues/397#event-603857030](https://github.com/thx/RAP/issues/397#event-603857030)  
我更换了TOMCAT版本部署仍然没解决，更换操作系统有点发现。  
windows使用tomcat8部署没有问题，页面可正常访问。这个可以说明WAR包、DB和REDIS的配置没有问题。  
linux上面部署启动没有报错，访问页面返回404，日志如下：
```  
27-Mar-2016 10:23:06.446 INFO [pool-1-thread-1] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [java.util.concurrent.ScheduledFuture]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.util.concurrent.ScheduledFuture]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
        at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
        at org.apache.logging.log4j.core.util.WatchManager.stop(WatchManager.java:75)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.stop(AbstractConfiguration.java:332)
        at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:303)
        at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:262)
        at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$1.run(DefaultShutdownCallbackRegistry.java:100)
        at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
        at java.lang.Thread.run(Thread.java:745)
```  
linux上面配置了JDK和TOMCAT的环境变量：
```  
JAVA_HOME=/usr/java/jdk1.8.0_60
export JAVA_HOME
CATALINA_HOME=/app/tomcat8
export CATALINA_HOME
CLASSPATH=.:$JAVA_HOME/lib:$CATALINA_HOME/common/lib
export CLASSPATH
PATH=$PATH:$HOME/bin:$JAVA_HOME/bin
export PATH  
```  
linux系统信息：Linux cnsz22vl0399 2.6.32-504.el6.x86_64 #1 SMP Tue Sep 16 01:56:35 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux  

请问linux上面部署需要注意哪些问题？

**Comment by fahai** [comment]
我把在windows上面可以正常跑的整个tomcat文件夹丢到linux，居然可以了。
