### ISSUE TITLE
保存项目信息(包括tb_action信息)异常

### ISSUE THREAD

**Issue by fahai** [thx/RAP#468]
异常信息：
```  
technical details
Unknown Exception
java.lang.NullPointerException at com.taobao.rigel.rap.organization.service.impl.OrganizationMgrImpl.canUserManageProject(OrganizationMgrImpl.java:198) at sun.reflect.GeneratedMethodAccessor248.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) at com.sun.proxy.$Proxy51.canUserManageProject(Unknown Source) at com.taobao.rigel.rap.workspace.web.action.WorkspaceAction.checkIn(WorkspaceAction.java:379) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:891) at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1293) at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68) at 
```  

前段提示错误：
```  
POST http://10.202.4.102:8080/workspace/checkIn.do net::ERR_CONNECTION_ABORTED  base.js?_r=20151111.v0.14.0:2273 
```  

请求参数：
```  
id:1
projectData:{"json 内容"}
deletedObjectListData:[]
versionPosition:4
description:quick save  
```  

project表数据：
```  
    id  NAME         USER_ID          CREATE_DATE  
------  -----------  -------  ---------------------
     1  ESGL        2    2016-03-27 00:00:00
```

**Comment by Bosn** [comment]
最近项目有升级么？什么版本

升级项目的时候注意按照DATABASE_CHANGE.MD进行数据库结构更新。

**Comment by fahai** [comment]
版本：V0.14.0
项目没有升级。
系统现在建了两个项目，一个项目id是1，另一个项目id是2，项目1前段时间使用正常，现在保存不了信息进去，项目2可以。还可从哪方面定位这个原因？

**Comment by Bosn** [comment]
先升级到最新吧，14 到 14.1只覆盖war包就好了，没有数据库改动

**Comment by fahai** [comment]
升级到 14.1问题依然存在。
能不能提供一下备份项目数据的SQL脚本，我打算新建一个项目3，再把数据一部分一部分得迁移过去？

**Comment by Bosn** [comment]
你把提交的数据，发到我邮箱。bosn@outlook.com 我本机看看能不能复现

**Comment by loviselu** [comment]
@fahai @Bosn 遇到一样的问题了，请问最后是怎么解决的？
