### ISSUE TITLE
v0.14.2版本中mock出错

### ISSUE THREAD

**Issue by lzzhoujielun** [thx/RAP#600]
{
  "salt": "262594089018",
  "message": "success",
  "body": [
    {
      "hotelId": 1,
      "hotelName": "aaa"
    },
    {
      "hotelId": 2,
      "hotelName": "bbb"
    },
    {
      "hotelId": 3,
      "hotelName": "ccc"
    },
    {
      "hotelId": 4,
      "hotelName": "ddd"
    },
    {
      "hotelId": 5,
      "hotelName": "eee"
    }
  ],
  "status": 200
}

java.nio.file.NoSuchFileException: D:\apache-tomcat-8.0.36\webapps\ROOTstat\js\util\mock-min.js
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at com.taobao.rigel.rap.common.utils.MockjsRunner.getMockjsCode(MockjsRunner.java:31)
	at com.taobao.rigel.rap.common.utils.MockjsRunner.initMockjs(MockjsRunner.java:58)
	at com.taobao.rigel.rap.common.utils.MockjsRunner.<init>(MockjsRunner.java:26)
	at com.taobao.rigel.rap.common.utils.MockjsRunner.renderMockjsRule(MockjsRunner.java:42)
	at com.taobao.rigel.rap.mock.service.impl.MockMgrImpl$1.call(MockMgrImpl.java:205)
	at com.taobao.rigel.rap.mock.service.impl.MockMgrImpl$1.call(MockMgrImpl.java:203)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
mock抛 {"errMsg":"\"Mock\" is not defined.","isOk":false}错误 麻烦帮忙看下

**Comment by k19421** [comment]
你是在什么情况下出现的这个问题？
还有0.14.2在哪儿下载的？我只看到有0.14.1啊？
并且上午刚部署了0.14.1能够正常使用

**Comment by lzzhoujielun** [comment]
点击数据mock的时候 mock抛 {"errMsg":"\"Mock\" is not defined.","isOk":false}

**Comment by lzzhoujielun** [comment]
code源代码 down下载就是0.14.2

**Comment by k19421** [comment]
参考这个   [#412](https://github.com/thx/RAP/issues/412)
在不改源码的情况下，修改Tomcat的配置文件server.xml
在Host下面加一个配置
<Context path="/" docBase="你的tomcat目录\webapps\ROOT\" debug="0" reloadable="true">   

注意上面的docBase最后一定要加一个\

**Comment by k19421** [comment]
`<Context path="/" docBase="你的tomcat\webapps\ROOT\" debug="0" reloadable="true"> `

**Comment by lzzhoujielun** [comment]
@k19421 谢谢，之前修改源代码解决了，不过你告知的这个方式我认为更合理

**Comment by puregardenia** [comment]
加上`<Context path="/" docBase="D:\Program Files\Tomcat 8.5\webapps\ROOT\" debug="0" reloadable="true"> ` 以后tomcat启动不了。。。

**Comment by k19421** [comment]
@puregardenia 加的Context标签是不是没关闭？

**Comment by puregardenia** [comment]
@k19421 关闭以后，tomcat 可以启动了，但是好像不起作用，地址改成 mockjsdata 输入``http://localhost:8080/mockjsdata/1/getUserList``还是报错啊，我没改.java源代码，这个问题不知道下个版本能解决不，官网 http://rap.taobao.org/ 上使用mockjsdata是正确的。
报错信息
```
{
    "errMsg": "\"Mock\" is not defined.",
    "isOk": false
}
```

**Comment by lzzhoujielun** [comment]
@puregardenia 实在不行可以直接修改源码 把FileUtils类中JS_UTIL_DIR_PATH静态变量加上File.separator分隔符试试
