### ISSUE TITLE
响应参数里导入json后无法保存

### ISSUE THREAD

**Issue by rainytooo** [thx/RAP#716]
`
2016-10-31 09:56:27.626:WARN:oejs.session:Scheduler-991505714: Problem scavenging sessions
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
        at com.taobao.rigel.rap.common.listener.SessionListener.sessionDestroyed(SessionListener.java:42)
        at org.eclipse.jetty.server.session.AbstractSessionManager.removeSession(AbstractSessionManager.java:794)
        at org.eclipse.jetty.server.session.AbstractSession.timeout(AbstractSession.java:310)
        at org.eclipse.jetty.server.session.HashSessionManager.scavenge(HashSessionManager.java:362)
        at org.eclipse.jetty.server.session.HashSessionManager$Scavenger.run(HashSessionManager.java:84)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-10-31 11:42:31.297:WARN:oejs.ServletHandler:qtp1586600255-19: /workspace/checkIn.do
java.lang.IllegalStateException: Form too large: 201739 > 200000
        at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:497)
        at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:435)
        at org.eclipse.jetty.server.Request.getParameters(Request.java:365)
        at org.eclipse.jetty.server.Request.getParameterMap(Request.java:1006)
        at org.apache.struts2.dispatcher.Dispatcher.createContextMap(Dispatcher.java:631)
        at org.apache.struts2.dispatcher.ng.PrepareOperations.createActionContext(PrepareOperations.java:81)
        at org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:89)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.springframework.orm.hibernate5.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at com.taobao.rigel.rap.common.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:118)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
        at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
        at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
        at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at com.taobao.rigel.rap.common.filter.AuthCheckFilter.doFilter(AuthCheckFilter.java:122)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at com.alibaba.buc.sso.client.filter.SSOFilter.doFilter(SSOFilter.java:96)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
`

原始json如下:

`
{
  "count": 5,
  "next": "",
  "previous": "",
  "results": [
    {
      "id": 5,
      "create_date": "2016-10-30T14:23:27.554703Z",
      "create_date_st": 1477837407,
      "update_date": "2016-10-30T14:23:27.554757Z",
      "update_date_st": 1477837407,
      "start_time": "2016-10-30T08:57:31Z",
      "start_time_st": 1477817851,
      "end_time": "2016-10-30T14:23:01Z",
      "end_time_st": 1477837381,
      "title": "adadadasd",
      "room": {
        "create_date": "2016-10-27T09:19:28.444048Z",
        "create_date_st": 1477559968,
        "update_date": "2016-10-31T02:20:52.222551Z",
        "update_date_st": 1477880452,
        "id": 4,
        "room_id": "568166",
        "room_name": "随便来一个11",
        "anchor_id": "20628",
        "anchor_nick": "仁波切",
        "room_status": 1
      },
      "speaker": "",
      "duration": 19529,
      "play_url": "http://open.talk-fun.com/play/PD0-JSYgImggaiEh.html?st=ln9GyaoC-3GpoIjf64kUig&e=1508941404",
      "live_id": "1315721"
    },
    {
      "id": 4,
      "create_date": "2016-10-29T15:53:11.368242Z",
      "create_date_st": 1477756391,
      "update_date": "2016-10-29T15:53:11.368311Z",
      "update_date_st": 1477756391,
      "start_time": "2016-10-29T13:44:46Z",
      "start_time_st": 1477748686,
      "end_time": "2016-10-29T15:52:42Z",
      "end_time_st": 1477756362,
      "title": "oss-oss-img-guide-cn-zh-2016-08-23",
      "room": {
        "create_date": "2016-10-27T09:19:28.444048Z",
        "create_date_st": 1477559968,
        "update_date": "2016-10-31T02:20:52.222551Z",
        "update_date_st": 1477880452,
        "id": 4,
        "room_id": "568166",
        "room_name": "随便来一个11",
        "anchor_id": "20628",
        "anchor_nick": "仁波切",
        "room_status": 1
      },
      "speaker": "",
      "duration": 7675,
      "play_url": "http://open.talk-fun.com/play/PD0-JSIrK2ggaiIq.html?st=BO-Ud2YLlyD-93VDk3xC7Q&e=1508860390",
      "live_id": "1315398"
    },
    {
      "id": 3,
      "create_date": "2016-10-29T13:43:24.453241Z",
      "create_date_st": 1477748604,
      "update_date": "2016-10-29T13:43:24.453303Z",
      "update_date_st": 1477748604,
      "start_time": "2016-10-29T12:19:38Z",
      "start_time_st": 1477743578,
      "end_time": "2016-10-29T13:42:18Z",
      "end_time_st": 1477748538,
      "title": "akjshdkahdas8-23",
      "room": {
        "create_date": "2016-10-27T09:19:28.444048Z",
        "create_date_st": 1477559968,
        "update_date": "2016-10-31T02:20:52.222551Z",
        "update_date_st": 1477880452,
        "id": 4,
        "room_id": "568166",
        "room_name": "随便来一个11",
        "anchor_id": "20628",
        "anchor_nick": "仁波切",
        "room_status": 1
      },
      "speaker": "",
      "duration": 4958,
      "play_url": "http://open.talk-fun.com/play/PD0-JSIqKmggaiEr.html?st=7wsWwWK984yI8Wbvt2y7Fw&e=1508852596",
      "live_id": "1315389"
    },
    {
      "id": 2,
      "create_date": "2016-10-29T03:30:06.474966Z",
      "create_date_st": 1477711806,
      "update_date": "2016-10-29T03:30:06.475018Z",
      "update_date_st": 1477711806,
      "start_time": "2016-10-29T03:00:02Z",
      "start_time_st": 1477710002,
      "end_time": "2016-10-29T03:00:18Z",
      "end_time_st": 1477710018,
      "title": "5456456oooo",
      "room": {
        "create_date": "2016-10-27T09:19:28.444048Z",
        "create_date_st": 1477559968,
        "update_date": "2016-10-31T02:20:52.222551Z",
        "update_date_st": 1477880452,
        "id": 4,
        "room_id": "568166",
        "room_name": "随便来一个11",
        "anchor_id": "20628",
        "anchor_nick": "仁波切",
        "room_status": 1
      },
      "speaker": "",
      "duration": 15,
      "play_url": "http://open.talk-fun.com/play/PD0-JSEjJ2ggaiMo.html?st=rb208kpFUPEZkCHJez3VRw&e=1508815803",
      "live_id": "1315014"
    },
    {
      "id": 1,
      "create_date": "2016-10-29T03:07:34.371243Z",
      "create_date_st": 1477710454,
      "update_date": "2016-10-29T03:07:34.371299Z",
      "update_date_st": 1477710454,
      "start_time": "2016-10-29T03:05:36Z",
      "start_time_st": 1477710336,
      "end_time": "2016-10-29T03:07:14Z",
      "end_time_st": 1477710434,
      "title": "oss-oss-img-guide-cn-zh-2016-08-23",
      "room": {
        "create_date": "2016-10-27T09:19:28.444048Z",
        "create_date_st": 1477559968,
        "update_date": "2016-10-31T02:20:52.222551Z",
        "update_date_st": 1477880452,
        "id": 4,
        "room_id": "568166",
        "room_name": "随便来一个11",
        "anchor_id": "20628",
        "anchor_nick": "仁波切",
        "room_status": 1
      },
      "speaker": "",
      "duration": 97,
      "play_url": "http://open.talk-fun.com/play/PD0-JSEgJ2ggaiUr.html?st=cIVGeqoECdpDrLp7CiLWfw&e=1508814451",
      "live_id": "1315024"
    }
  ]
}
`

**Comment by rainytooo** [comment]
已解决,修改了jetty的参数
`
<Call name="setAttribute">
    <Arg>org.eclipse.jetty.server.Request.maxFormContentSize</Arg>
    <Arg>100000</Arg>
   </Call>
  <Call name="setAttribute">
    <Arg>org.eclipse.jetty.server.Request.maxFormKeys</Arg>
    <Arg>2000</Arg>
   </Call>`
