### ISSUE TITLE
            当你不幸走入该页面时，说明系统出现了不可处理的错误，或您进行了比较BT的操作导致系统不能处理，相关信息我们已经记录，并且会尽快解决，当然，也欢迎您联系平台的维护人员，谢谢哟。 T.T

### ISSUE THREAD

**Issue by jayluns** [thx/RAP#799]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>我勒个去！出错了 T.T </title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="/stat/img/favicon.ico">
        <link rel="stylesheet" href="/stat/bootstrap/css/bootstrap.min.css?_r=20151111.v0.14.0">
        
        
        
        <link rel="stylesheet" href="/stat/css/rap.template.css?_r=20151111.v0.14.0" type="text/css" media="screen">
        <link rel="stylesheet" href="/stat/js/ui/floater/css/floater.css?_r=20151111.v0.14.0" type="text/css">
        <script type="text/javascript" src="/stat/js/core/jquery-2.1.4.min.js?_r=20151111.v0.14.0"></script>
        <script type="text/javascript" src="/stat/js/core/tangram-1.2.1.js?_r=20151111.v0.14.0"></script>
        <script type="text/javascript" src="/stat/js/core/tangram-fix.js?_r=20151111.v0.14.0"></script>
        <script type="text/javascript" src="/stat/js/base.js?_r=20151111.v0.14.0"></script>
        <script type="text/javascript" src="/stat/js/routes.js?_r=20151111.v0.14.0"></script>
        <script type="text/javascript" src="/stat/bootstrap/js/bootstrap.min.js?_r=20151111.v0.14.0"></script>
        <script type="text/javascript" src="/stat/js/core/ecui-1.1.0-br.js?_r=20151111.v0.14.0"></script>
        <script type="text/javascript" src="/stat/js/ui/floater/js/floater.js?_r=20151111.v0.14.0"></script>
        <script type="text/javascript" src="/stat/js/core/rap.js?_r=20151111.v0.14.0"></script>
    </head>
    <body>
        <script>
    function getUsers(callback, teamId) {
        if ($.local('users')) {
            callback($.local('users'));
            return;
        }
        var params = {};
        if (teamId) {
            params.id = teamId;
        }
        $.get($.route('org.account.all'), params, function (data) {
            users = data.users;
            $.local('users', users);
            callback(users);
        }, "JSON");
    }
</script>
        <div class="navbar navbar-inverse" role="navigation" style="border-radius: 0;">
            
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#global-navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">
                        <i class="iconlogo mi-rap"></i>
                        <span class="logo-text">
                            <span id="rap-logo-text">RAP</span>
                            <span>v0.14.12</span>
                            <span style="color:#cc0000; font-size:10px;">&nbsp;&nbsp;beta</span>
                        </span>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="global-navbar">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="/platform/home.do">主页</a>
                        </li>
                        <li>
                            <a href="https://github.com/thx/RAP/wiki/home_cn" target="_blank">文档</a>
                        </li>
                        <li style="display:none;">
                            <a href="/platform/test.do">测试</a>
                        </li>
                        <li>
                            <a href="/platform/log.do">数据</a>
                        </li>
                        <li>
                            <a href="http://thx.github.io/RAP/study.html" target="_blank">教程
                        
                                
                    
                            </a>
                        </li>
                    </ul>
                    <div class="pull-right">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="javascript:void(0);" class="dropdown-toggle" id="login-trigger">登录</a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li>
                                        <form name="formMain" class="navbar-form login-form"
                                              action="/account/doLogin.do" method="post">
                                            <input class="span2 form-control" style="width:200px" type="text"
                                                   placeholder="用户名" required name="account">
                                            <input class="span2 form-control" style="width:200px;margin-top:10px;"
                                                   type="password" required placeholder="密码" name="password">
                                            
                                    <input name="kaptcha" class="form-control" type="text" value="" placeholder="请输入验证码" style="width:200px;margin-top:10px;">
                                    <img src="/Kaptcha.jpg" onclick="this.src='/Kaptcha.jpg?' + Math.random()" style="margin-top: 5px;">
                                    <div style="margin-top: 10px;">
                                        <button type="submit" class="btn btn-primary" id="login-btn">登录</button>
                                        <button type="button" class="btn btn-default" id="cancel-login-btn"
                                                        style="margin-left: 10px;">取消
                                                </button>
                                    </div>
                                </form>
                            </li>
                            <li style="display:none;" class="divider"></li>
                            <li style="display:none;">
                                <div class="navbar-form">
                                    <a href="https://login.alibaba-inc.com/ssoLogin.htm?APP_NAME=rapauto&BACK_URL=http%3A%2F%2F10.100.112.197%3A8080&CANCEL_CERT=true&CLIENT_VERSION=0.3.9&CONTEXT_PATH=%2F">
                                        <span class="btn btn-warning other-login-btn sso-login">用阿里域账号登录</span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:void(0);" class="dropdown-toggle" id="register-trigger">注册</a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>
                                <form name="formMain" class="navbar-form register-form"
                                              action="/account/doRegister.do" method="post">
                                    <input class="span2 form-control" style="width:200px" type="text"
                                                   placeholder="中文名" required name="name">
                                    <input class="span2 form-control" style="width:200px;margin-top:10px;"
                                                   type="email" placeholder="邮箱" required name="email">
                                    <input class="span2 form-control" style="width:200px;margin-top:10px;"
                                                   type="text" placeholder="登录用户名" required name="account">
                                    <input class="span2 form-control" style="width:200px;margin-top:10px;"
                                                   type="password" placeholder="密码" required name="password"
                                                   id="register-password">
                                    <input class="span2 form-control" style="width:200px;margin-top:10px;"
                                                   type="password" placeholder="密码确认" required name="passwordConfirm"
                                                   id="register-password-confirm">
                                    <input name="kaptcha" class="form-control" type="text" value="" placeholder="请输入验证码" style="width:200px;margin-top:10px;">
                                    <img src="/Kaptcha.jpg" onclick="this.src='/Kaptcha.jpg?' + Math.random()" style="margin-top: 5px;">
                                    <div style="margin-top: 10px;">
                                        <button type="submit" class="btn btn-primary" id="register-btn">注册
                                                </button>
                                        <button type="button" class="btn btn-default" id="cancel-register-btn"
                                                        style="margin-left: 10px;">取消
                                                </button>
                                    </div>
                                </form>
                            </li>
                            <li style="display:none;" class="divider"></li>
                            <li style="display:none;">
                                <div class="navbar-form">
                                    <a href="https://login.alibaba-inc.com/ssoLogin.htm?APP_NAME=rapauto&BACK_URL=http%3A%2F%2F10.100.112.197%3A8080&CANCEL_CERT=true&CLIENT_VERSION=0.3.9&CONTEXT_PATH=%2F">
                                        <span class="btn btn-warning other-login-btn sso-login">用阿里域账号登录</span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        
        
    </div>
    
    
</div>

<div class="container">
    <div id="error">
        <div class="title">
            <h2>RAP出错啦！</h2>
        </div>
        <div class="alert alert-danger" role="alert">
                    当你不幸走入该页面时，说明系统出现了不可处理的错误，或您进行了比较BT的操作导致系统不能处理，相关信息我们已经记录，并且会尽快解决，当然，也欢迎您联系平台的维护人员，谢谢哟。 T.T
            </div>
        <div id="image-error"></div>
        <div class="title">
            <h2>technical details</h2>
        </div>
        <div class="message content">
                            String index out of range: -1
                    </div>
        <div class="detail">
                            java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1871)
	at com.taobao.rigel.rap.common.utils.URLUtils.getRelativeUrl(URLUtils.java:85)
	at com.taobao.rigel.rap.project.dao.impl.ProjectDaoImpl.getMatchedActionList(ProjectDaoImpl.java:386)
	at com.taobao.rigel.rap.project.service.impl.ProjectMgrImpl.getMatchedActionList(ProjectMgrImpl.java:289)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy202.getMatchedActionList(Unknown Source)
	at com.taobao.rigel.rap.mock.service.impl.MockMgrImpl.generateRule(MockMgrImpl.java:353)
	at com.taobao.rigel.rap.mock.service.impl.MockMgrImpl.generateRuleData(MockMgrImpl.java:219)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy206.generateRuleData(Unknown Source)
	at com.taobao.rigel.rap.mock.web.action.MockAction.createMockjsData(MockAction.java:363)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:892)
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1294)
	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
	at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethodWithDebugInfo(XWorkMethodAccessor.java:117)
	at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethod(XWorkMethodAccessor.java:108)
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1370)
	at ognl.ASTMethod.getValueBody(ASTMethod.java:91)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.Ognl.getValue(Ognl.java:467)
	at ognl.Ognl.getValue(Ognl.java:431)
	at com.opensymphony.xwork2.ognl.OgnlUtil$3.execute(OgnlUtil.java:352)
	at com.opensymphony.xwork2.ognl.OgnlUtil.compileAndExecuteMethod(OgnlUtil.java:404)
	at com.opensymphony.xwork2.ognl.OgnlUtil.callMethod(OgnlUtil.java:350)
	at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:430)
	at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:290)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:251)
	at org.apache.struts2.interceptor.DeprecationInterceptor.intercept(DeprecationInterceptor.java:41)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.interceptor.debugging.DebuggingInterceptor.intercept(DebuggingInterceptor.java:256)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:168)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:265)
	at org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:76)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.intercept(ConversionErrorInterceptor.java:138)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:229)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:229)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.StaticParametersInterceptor.intercept(StaticParametersInterceptor.java:191)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:73)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.interceptor.DateTextFieldInterceptor.intercept(DateTextFieldInterceptor.java:125)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:91)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.interceptor.FileUploadInterceptor.intercept(FileUploadInterceptor.java:253)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ModelDrivenInterceptor.intercept(ModelDrivenInterceptor.java:100)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ScopedModelDrivenInterceptor.intercept(ScopedModelDrivenInterceptor.java:141)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ChainingInterceptor.intercept(ChainingInterceptor.java:145)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:140)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:164)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.AliasInterceptor.intercept(AliasInterceptor.java:193)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:189)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.intercept(ConversionErrorInterceptor.java:138)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:229)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.StaticParametersInterceptor.intercept(StaticParametersInterceptor.java:191)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ModelDrivenInterceptor.intercept(ModelDrivenInterceptor.java:100)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ChainingInterceptor.intercept(ChainingInterceptor.java:145)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:140)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:164)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.AliasInterceptor.intercept(AliasInterceptor.java:193)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:189)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.interceptor.CreateSessionInterceptor.intercept(CreateSessionInterceptor.java:101)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:245)
	at org.apache.struts2.impl.StrutsActionProxy.execute(StrutsActionProxy.java:54)
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:567)
	at org.apache.struts2.dispatcher.ng.ExecuteOperations.executeAction(ExecuteOperations.java:81)
	at org.apache.struts2.dispatcher.ng.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:99)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:213)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.taobao.rigel.rap.common.filter.AuthCheckFilter.doFilter(AuthCheckFilter.java:122)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.alibaba.buc.sso.client.filter.SSOFilter.doFilter(SSOFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

                    </div>
    </div>
    <footer style="margin-top: 40px; text-align: center;">
        <p>
            <span id="_logOnline">-</span>
            <span>人在使用 RAP，今日 Mock 服务被调用</span>
            <span id="_logMockNumToday">-</span>
            <span>次</span>
            <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");
            document.write(unescape("%3Cspan id='cnzz_stat_icon_5879641'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "v1.cnzz.com/stat.php%3Fid%3D5879641%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));</script>
        </p>
    </footer>
    <script>
        function _logData() {
            if (window.localStorage) {
                if (window.localStorage.getItem('stopLogData')) {
                    return;
                }
            }
            jQuery.ajax({
                url: '/account/logData.do',
                success: function (data) {
                    data = JSON.parse(data);
                    $('#_logOnline').html(data.online);
                    $('#_logMockNumToday').html(data.mockNumToday);
                    var ele = $('#mockDataInDashboard');
                    if (ele.length) {
                        var startMockNum = +ele.attr('data-start');
                        ele.html(startMockNum + (+data.mockNumToday));
                    }
                    // setTimeout(_logData, 2000);
                }
            });
        }
        _logData();
    </script>
</div>

<script type="text/tmpl" id="_create-team-tmpl">
    <form id="_formCreateTeam">
        <div class="form-horizontal" role="form">
            <div class="form-group">
                <label class="col-sm-2 control-label">
                团队名称
                
                    <span style="color:red">
                    *
                </span>
                </label>
                <div class="col-sm-10">
                    <input type="text" id="_createTeamName" required class="form-control" style="width:432px;" placeholder="请在此编辑团队名称"
                value="{{name}}" />
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-2 control-label">
                权限
            </label>
                <div class="col-sm-10">
                    <input type="radio" value="1" id="_createTeamType1" checked="checked" name="_createTeamType"
                />
                    <label for="_createTeamType1">
                    仅团队成员可见
                </label>
                    <input type="radio" value="2" id="_createTeamType2" name="_createTeamType"
                />
                    <label for="_createTeamType2">
                    全员可见
                </label>
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-2 control-label">
                团队描述
            </label>
                <div class="col-sm-10">
                    <textarea class="form-control desc" id="_createTeamDesc" style="width:432px;resize:vertical;" placeholder="请在此编辑团队描述">{{desc}}</textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="" class="col-sm-2 control-label">
                团队成员
            </label>
                <div class="col-sm-10 picking-user"  style="position:relative">
                {{#users}}
                
                    <span class="picked-user" data-name="{{name}}" data-account="{{account}}" title="{{account}} ({{name}})">
                    {{account}} ({{name}})
                    
                        <i class="unpick-btn">
                        &times;
                    </i>
                    </span>
                {{/users}}
                    <input class="form-control accounts-inputer" placeholder="添加项目成员" id="_createTeamMemberList" />
                    <span class="user-loading">
                    项目成员列表加载中，请稍候~
                </span>
                    <span class="glyphicon glyphicon-question-sign tip" title="如果该用户没有登录/注册过RAP，系统中就没有TA的信息。请TA先登录一下RAP吧。匹配时请可以输入TA的花名或帐号(域帐号)">
                    找不到TA?
                </span>
                    <div class="accounts-con">
                </div>
                </div>
            </div>
        </div>
    </form>
</script>
<script type="text/tmpl" id="user-auto-list">
    <ul class="autocompleter">
        {{#users}}
            
        <li data-account="{{account}}" data-name="{{name}}" {{^block}}title="{{account}} ({{name}})"{{/block}}{{#block}} data-block="true"{{/block}}>
                {{#block}}没有更多匹配数据{{/block}}
                {{^block}}{{account}} ({{name}}){{/block}}
            </li>
        {{/users}}
    </ul>
</script>
<script type="text/tmpl" id="user-item-tmpl">
    <span class="picked-user" data-name="{{name}}" data-account="{{account}}" title="{{account}} ({{name}})">{{account}} ({{name}})
        <i class="unpick-btn">&times;</i>
    </span>
</script>
<script>
    function _bindCreateTeamDialogAutoCompleteEvents() {
        var that = this;

        $.confirm({
            content: $.render($('#_create-team-tmpl').text(), {}),
            title: '创建团队',
            confirmText: '确认创建',
            cancelCallback: function () {

            },
            showCallback: function () {
                var that = this;
                $(this).find('input[type=text]').focus();
                $(this).find('.picking-user').delegate('.unpick-btn', 'click', function () {
                    $(this).parent('.picked-user').remove();
                });
                $('.tip').tooltip();
                getUsers(function (users) {
                    $('.user-loading').hide();
                    $(that).find('.accounts-inputer').keyup(function () {
                        $.autocomplete(that, users);
                    }).focus(function () {
                        $.autocomplete(that, users);
                    });
                });
            },
            confirmClicked: function () {
                var modal = $(this);
                var name = $('#_createTeamName').val();
                var desc = $('#_createTeamDesc').val();
                var isPrivate = $('#_createTeamType1')[0].checked;
                var pickedUserList = [];
                $('.picked-user').each(function (index, ele) {
                    pickedUserList.push($(ele).data('account'));
                });
                $.post($.route('org.team.create'), {
                    name: name,
                    desc: desc,
                    accessType: isPrivate ? 10 : 20,
                    accountList: pickedUserList.join(',')
                }, function (data) {
                    modal.modal('hide');
                    window.location.href = "/org/productline.do" + "?id=" + data.id
                }, "JSON");
            }
        });

    }

    function _bindTemplateEvents() {
        $('body').delegate('._createTeamBtn', 'click', _bindCreateTeamDialogAutoCompleteEvents);
        $('.glyphicon').tooltip();
    }

    setTimeout(function() {
        $('#jobHref').attr('style', '');
    }, 2000);

    _bindTemplateEvents();
</script>
<script>
    function responsiveTeamList() {
        // TODO
    }
    responsiveTeamList()
</script>
</body>
</html>

**Comment by jayluns** [comment]
截取字符串的时候报错了

**Comment by huanggm** [comment]
我也借宝地反馈一个CASE吧

我也进入到这个错误页面了，根据我反复尝试，得出的结论是：

在请求接口的时候，如果有id这个参数，那么id必须是整数，而且不能是特别大的整数（溢出了），否则就会报错


比如这个链接：
http://localhost:8080/mockjs/1/supplyer/detail?_c=jQuery22409653776021498046_1486177192111&_=1486177192116&id=123a

因为id=123a所以报错了

**Comment by guodefu909** [comment]
如果有id这个参数，那么id必须是整数，而且不能是特别大的整数（溢出了），否则就会报错

是的，我也是遇到这个问题，怀疑id被RAP占用了

**Comment by huanggm** [comment]
@mock=@integer(1,99999)

这样设置就可以了
