### ISSUE TITLE
rap.taobao.com 挂了

### ISSUE THREAD

**Issue by jy03078959** [thx/RAP#808]
线上服务挂了
technical details
Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection
org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection at org.springframework.orm.hibernate5.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:541) at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:427) at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) at com.sun.proxy.$Proxy46.getUser(Unknown Source) at com.taobao.rigel.rap.account.web.action.AccountAction.myAccount(AccountAction.java:395) at sun.reflect.GeneratedMethodAccessor565.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:892) at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1294) at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68) at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethodWithDebugInfo(XWorkMethodAccessor.java:117) at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethod(XWorkMethod

**Comment by xiaoxing598** [comment]
如果是在实际项目中使用，建议公司内部独立部署一套服务。

**Comment by vincentzhwg** [comment]
还是一直打不开

**Comment by dogdong** [comment]
咋办啊！！！！！！！

**Comment by Robinxingxing** [comment]
rap挂啦

**Comment by xifeimen** [comment]
官方没人回复吗？急呀！

**Comment by jiangbaotian** [comment]
求帮忙，线上RAP挂掉，公司文档在里面

**Comment by Robinxingxing** [comment]
做一套自己本地的吧，放在作者这边确实有点不保险

**Comment by xifeimen** [comment]
首先得把数据导出来！！！

**Comment by Robinxingxing** [comment]
嗯嗯

**Comment by liujian1983** [comment]
我也遇到这个问题，后来找了开发的一个大大看了下。实际还是部署问题。
解决办法:
ROOT.WAR放到webapp目录，第一次启动TOMCAT后，修改config.properties,添加数据库名称和密码。
之后！！！！！！-----请删除webapp目录下的ROOT.WAR。然后再重新启动TOMCAT。

报错原因：因为如果ROOT.WAR不删除，每次执行startup.bat启动TOMCAT的时候，默认是读取ROOT.WAR，而里面是没有数据库配置的。-----我是WINDOWS部署。

有类似的同学，可以试试。

**Comment by bibodeng** [comment]
公司文档在里面，有维护的同学尽快恢复下吗
